### ISSUE TITLE
fix zeropoints in converting to counts

### ISSUE THREAD

**Issue by pbrown801** [pbrown801/aggienova-templates#3]
observedmags_to_counts.py should use findzeropoints.py to use different zeropoints for each filter when converting from magnitudes to counts

**Comment by TateWalker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Get zeropoints for every filter](https://trello.com/c/fkVJnMsS/10-get-zeropoints-for-every-filter)

**Comment by pbrown801** [comment]
Noah calculated the zeropoints and put them in filterfiles_to_filterfilelist to be output as an array of zeropoints corresponding to the input filter list
